src/config/routes.rb
# Railsアプリケーションのルーティングを定義しています。
# ユーザーが特定のURLにアクセスした際に、どのコントローラーのどのアクションを呼び出すかを指定します。
Rails.application.routes.draw do
  # 'home/top' にアクセスがあった場合、'home' コントローラーの 'top' アクションを呼び出します。
  # これは、アプリケーションのルートURLに対する設定で、ユーザーが最初にアプリケーションにアクセスしたときに表示されるページを指定します。
  root to: 'home#top'

  # Devise gem が提供するユーザー認証関連のルーティングを自動的に生成します。
  # これにより、ユーザーのサインアップやログインなどの認証機能を実装できます。
  devise_for :users

  # resource メソッドは、単一のリソースに対する CRUD 操作を扱う際に使用されます。
  # これは、特定の画面での新規作成、編集、表示、更新などの操作を可能にします。
  # exceptは、指定したアクションは除外するという意味。
  resource :user, except: [:new, :create, :destroy]

  # 'articles' リソースに対するルーティングを設定します。
  # これにより、articlesコントローラーのindex、show、new、create、edit、update、destroyアクションに対応するURLが生成されます。
  resources :articles

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

src/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/models/article.rb
class Article < ApplicationRecord
  # 記事は一つのユーザーに所属することを示します。
  belongs_to :user
  
  with_options presence: true do
    # 以下のバリデーションが全ての属性に適用されることを示します。
    # presence: true は、それぞれの属性が空でないことを検証します。
    validates :title
    # タイトルが存在することを検証します。
    validates :body
    # 本文が存在することを検証します。
  end
end

src/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # デフォルトの Devise モジュールを含みます。利用可能な他のモジュールは以下の通りです:
  # :confirmable, :lockable, :timeoutable, :trackable, :omniauthable
  # 
  validates :name, presence: true
  # ユーザー名が存在することを検証します。
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Devise モジュールを使用して、ユーザーの認証に関連する機能を追加します。
  # :database_authenticatable: データベースを使用した認証を提供します。
  # :registerable: 新規登録機能を提供します。
  # :recoverable: パスワードのリセット機能を提供します。
  # :rememberable: ログイン情報の記憶機能を提供します。
  # :validatable: パスワードやメールアドレスのバリデーションを提供します。
  has_many :articles, dependent: :destroy
  # ユーザーが複数の記事を持つ関連を定義します。
  # dependent: :destroy は、ユーザーが削除された場合、関連するすべての記事も削除されることを示します。
end

src/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Devise コントローラーの場合にのみ実行するメソッドを設定
  # Devise コントローラーのアクションが呼び出される前に、configure_permitted_parameters メソッドを呼び出します。
  before_action :configure_permitted_parameters, if: :devise_controller?

  # ユーザーがサインインした後のリダイレクト先を指定するメソッド
  # サインイン後にユーザーをリダイレクトする先のパスを指定します。ここではユーザーの詳細ページにリダイレクトされます。
  def after_sign_in_path_for(resource)
    user_path
  end

  # ユーザーがサインアップした後のリダイレクト先を指定するメソッド
  # サインアップ後にユーザーをリダイレクトする先のパスを指定します。ここではユーザーの詳細ページにリダイレクトされます。
  def after_sign_up_path_for(resource)
    user_path
  end
  
  # ユーザーがサインアウトした後のリダイレクト先を指定するメソッド
  # サインアウト後にユーザーをリダイレクトする先のパスを指定します。ここではログインページにリダイレクトされます。
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end 

  protected

  # Devise の許可されたパラメーターを構成するメソッド
  # ユーザー登録時に許可されるパラメーターを指定します。
  # デフォルトでは、email と password のみが許可されていますが、ここでは name も追加されています。
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

src/app/controllers/articles_controller.rb
# ArticlesController: 記事関連の操作を処理するコントローラークラス
# ApplicationControllerを継承している。
class ArticlesController < ApplicationController
  # アクション: 記事一覧を表示するページ
  def index
    # データベースから全ての記事を取得し、@articlesという変数に代入する
    @articles = Article.all
  end

  # アクション: 特定の記事を表示するページ
  def show
    # 特定のIDに対応する記事をデータベースから取得し、インスタンス変数に代入する
    @article = Article.find(params[:id])
  end

  # アクション: 新しい記事を作成するページを表示する
  def new
    # 新しい記事のための空のArticleオブジェクトを生成し、インスタンス変数に代入する
    @article = Article.new
  end

  # アクション: 新しい記事をデータベースに保存する
  def create
    # フォームから送信された記事のパラメータを使って、新しいArticleオブジェクトを作成する
    @article = Article.new(article_params)
    # 現在ログインしているユーザーのIDを記事に関連付ける
    @article.user_id = current_user.id
    # 記事をデータベースに保存し、保存が成功した場合は記事の詳細ページにリダイレクトする
    if @article.save
      # 記事の作成が成功した場合の処理
      redirect_to article_path(@article), notice: '投稿に成功しました。'
    else
      # 保存が失敗した場合は、新規記事作成ページを再表示する
      render :new
    end
  end

  # アクション: 既存の記事を編集するページを表示する
  def edit
    # 編集対象の記事を特定し、インスタンス変数に代入する
    @article = Article.find(params[:id])
    # 現在ログインしているユーザーが記事の所有者でない場合は、不正なアクセスとしてリダイレクトする
    if @article.user_id != current_user.id
      redirect_to article_path, alert: '不正なアクセスです。もう一度やり直して下さい。'
    end
  end

  # アクション: 既存の記事を更新する
  def update
    # 編集対象の記事を特定し、インスタンス変数に代入する
    @article = Article.find(params[:id])
    # フォームから送信された記事のパラメータを使って、記事を更新する
    if @article.update(article_params)
      # 更新が成功した場合は、記事の詳細ページにリダイレクトする
      redirect_to article_path(@article), notice: "更新完了いたしました。"
    else
      # 更新が失敗した場合は、記事の編集ページを再表示する
      render :edit
    end
  end

  # アクション: 既存の記事を削除する
  def destroy
    # 削除対象の記事を特定し、ローカル変数に代入する
    article = Article.find(params[:id])
    # 記事をデータベースから削除する
    article.destroy
    # 記事一覧ページにリダイレクトする
    # 「#{article.title}」と書く事で、削除時のメッセージにタイトル名をつけることができる
    redirect_to articles_path, notice: "タイトル名『#{article.title}』を削除いたしました。"
  end

  # privateキーワードは、以下に続くメソッドがプライベートメソッドであることを示します。
  # つまり、外部から直接呼び出すことはできず、クラス内部でのみ利用可能です。
  private

  # Strong Parametersを使用して、フォームから受け取るパラメータを制限する
  def article_params
    params.require(:article).permit(:title, :body)
  end
end

src/app/controllers/home_controller.rb
# HomeControllerという名前のクラスを定義しています。
# これはRailsのコントローラークラスで、アプリケーションのコントローラーはこのクラスを継承します。
class HomeController < ApplicationController
  # topメソッドは、ホームページの表示に関連する処理を追加するための空のメソッドです。
  # 通常、このメソッドにはトップページの表示に必要なデータの取得やビューの表示処理が追加されます。
  def top
  end
end

src/app/controllers/users_controller.rb
# この行はUsersControllerというクラスを定義しています。
# < シンボルはUsersControllerが他のクラス、ApplicationControllerを継承していることを意味します。
# 継承により、UsersControllerはApplicationControllerのすべてのメソッドやプロパティを使用できます。
class UsersController < ApplicationController
  def show
    # この部分はUsersControllerクラス内にあるshowという名前のメソッドです。
    # Ruby on Railsでは、showメソッドは通常、単一のリソースを表示します。しばしばユーザープロフィールを表示するために使用されます。
    # このメソッドにはコードが含まれていないため、デフォルトでshow.html.erbというビューをレンダリングします。
    # show.html.erbファイル内で、特定のユーザーの詳細を表示できます。
  end

  def edit
    # 現在ログインしているユーザーの情報を取得して、@userに代入します。
    @user = current_user
  end
  
  def update
    # 現在ログインしているユーザーの情報を取得して、@userに代入します。
    @user = current_user
    # ユーザーの情報を更新し、更新が成功した場合はユーザーの詳細ページにリダイレクトします。
    # 更新が失敗した場合は、編集画面を再表示します。
    if @user.update(user_params)
      redirect_to user_path, notice: 'ユーザーを更新しました。'
    else
      render :edit
    end
  end
  
  private

  # ストロングパラメータ
  def user_params
    # ストロングパラメータを使用して、セキュリティ上の理由から許可された属性のみを受け入れます。
    # フォームから送信されたユーザー情報に対して、nameとemail属性のみを許可します。
    # これにより、不正なパラメータが送信された場合でも安全に処理できます。
    params.require(:user).permit(:name, :email)
  end
end

src/app/helpers/application_helper.rb
module ApplicationHelper
end

src/app/helpers/articles_helper.rb
module ArticlesHelper
end

src/app/helpers/home_helper.rb
module HomeHelper
end

src/app/helpers/users_helper.rb
module UsersHelper
end

src/app/views/articles/_errors.html.erb
<!--articleオブジェクトにエラーがあるかどうかをチェックしています。-->
<!--.any?メソッドは、articleオブジェクトにエラーがある場合に真を返します。-->
<% if article.errors.any? %>
  <!--articleオブジェクトにエラーがある場合に表示されるエラーメッセージを定義しています。-->
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><%= pluralize(article.errors.count, "error") %></h4>
    <p><%= pluralize(article.errors.count, "error") %> prohibited this object from being saved: not successfully</p>
    <hr>
    <p class="mb-0">
      <!--article.errors.full_messages.eachを使用して、各エラーメッセージがリストとして表示されます。-->
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </p>
  </div>
<% end %>

src/app/views/articles/_form.html.erb
<!--form_forヘルパーメソッドを使用して、articleオブジェクトに関連付けられたフォームを作成します。-->
<!--fは、フォームの各フィールドを定義するために使用します。-->
<%= form_for article do |f| %>
  <div class="form-group">
    <label>記事名</label>
    <!--記事のタイトルを入力するためのフィールドを定義しています。-->
    <!--text_fieldメソッドを使用してテキスト入力フィールドを生成します。-->
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>内容</label>
    <!--記事の本文を入力するためのフィールドを定義しています。-->
    <!--text_areaメソッドを使用してテキストエリアを生成します。-->
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <div>
    <!--フォームの送信ボタンを定義しています。-->
    <!--submitメソッドを使用して送信ボタンを生成-->
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

src/app/views/articles/edit.html.erb
<!-- '_errors' 部分テンプレートを呼び出して、@article オブジェクトに関連付けられたエラーメッセージを表示します。
     この部分テンプレートを使うことで、エラーメッセージの表示に関するコードを再利用しています。 -->
<%= render 'errors', article: @article %>

<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h2>編集</h2>
        <!-- '_form' 部分テンプレートを呼び出して、@article オブジェクトを渡します。
           これにより、記事の編集フォームが表示されます。 -->
        <%= render 'form', article: @article %>
    </div>
  </div>
</div>

src/app/views/articles/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-10 mx-auto">
      <!-- 記事一覧を表示するためのテーブルを作成します。 -->
      <table class="table table-hover">
        <!-- テーブルのヘッダー部分を定義します。 -->
        <thead class="thead-dark">
          <tr>
            <!-- 記事名の列を定義します。 -->
            <th scope="col">記事名</th>
            <!-- 投稿者の列を定義します。 -->
            <th scope="col">投稿者</th>
            <!-- 空の列を定義します。 -->
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <!-- @articles コレクション内の各記事に対してループします。 -->
          <% @articles.each do |article| %>
            <tr>
              <!-- 記事名をリンクとして表示し、記事の詳細ページにリンクします。 -->
              <td><%= link_to article.title, article_path(article) %> </td>
              <!-- 記事の投稿者の名前を表示します。 -->
              <td><%= article.user.name %></td>
              <!-- 空の列を追加します。 -->
              <td></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

src/app/views/articles/new.html.erb
<% if @article.errors.any? %>
  <!-- エラーメッセージを表示するアラート -->
  <div class="alert alert-danger" role="alert">
    <!-- エラーの数を表示 -->
    <h4 class="alert-heading"><%= pluralize(@article.errors.count, "error") %></h4>
    <!-- エラーメッセージの説明 -->
    <p><%= pluralize(@article.errors.count, "error") %> prohibited this object from being saved: not successfully</p>
    <hr>
    <p class="mb-0">
      <!-- 全てのエラーメッセージを繰り返し表示 -->
      <% @article.errors.full_messages.each do |message| %>
        <!-- 各エラーメッセージをリストアイテムとして表示 -->
        <li><%= message %></li>
      <% end %>
    </p>
  </div>
<% end %>

<!--この行は、_errorsという部分テンプレートを呼び出しています。これは、@articleオブジェクトに関連付けられたエラーメッセージを表示するためのものです。-->
<!--この部分テンプレートを使うことで、エラーメッセージの表示に関するコードを再利用しています。-->
<%= render 'errors', article: @article %>

<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h2>新規投稿</h2>
        <!-- '_form' 部分テンプレートを呼び出して、@articleオブジェクトを渡します。
           これにより、新規投稿フォームが表示されます。 -->
        <%= render 'form', article: @article %>
    </div>
  </div>
</div>

src/app/views/articles/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <!-- 投稿記事の表示をカード形式で行います -->
      <div class="card">
        <div class="card-body">
          <!-- 記事のタイトルを表示します -->
          <h5 class="card-title"><%= @article.title %></h5>
          <!-- 記事の本文を表示します。simple_formatメソッドは、改行を反映させます -->
          <p class="card-text"><%= simple_format @article.body %></p>
          <!-- 記事の更新日を表示します -->
          <p class="card-text">
            <small class="text-muted">更新日：<%= @article.updated_at.strftime("%Y-%m-%d") %></small>
          </p>
          <!-- ログインユーザーが記事の作成者である場合、編集と削除のリンクを表示します -->
          <% if @article.user == current_user %>
            <!--@articleは、articleコントローラのshowアクションに定義されている@article = Article.find(params[:id])の@article-->
            <!--要は、特定の記事のidを渡すことで、どの記事を「編集」若しくは「削除」を実施するのかを特定させる。-->
            <%= link_to '編集', edit_article_path(@article), class: "btn btn-success" %>
            <%= link_to '削除', article_path(@article), method: :delete, class: "btn btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

src/app/views/home/top.html.erb
<h1>Home#top</h1>
<p>Find me in app/views/home/top.html.erb</p>

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- ナビゲーションバーを定義 -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <!-- ロゴを表示し、ホームページへのリンクを提供 -->
      <%= link_to 'Article submission system', root_path, class: "navbar-brand" %>
      <!-- ナビゲーションの切り替えを行うボタン -->
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- 「ユーザーがログインしている場合」という意味 -->
       <!-- devise実装後、デフォルトで使用できる -->
      <% if user_signed_in? %>
        <!-- ナビゲーションメニュー -->
        <div class="collapse navbar-collapse" id="Navber">
          <!-- メニューアイテム -->
          <ul class="navbar-nav mr-auto">
            <!-- マイページへのリンク -->
            <li class="nav-item">
              <%= link_to 'マイページ', user_path, class: "nav-link" %>
            </li>
            <!-- 新規投稿へのリンク -->
            <li class="nav-item">
                <%= link_to '新規投稿', new_article_path, class: "nav-link" %>
            </li>
            <!-- 投稿一覧へのリンク -->
            <li class="nav-item">
                <%= link_to '投稿一覧', articles_path, class: "nav-link" %>
            </li>
            <!-- ログアウトへのリンク -->
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          </ul>
        </div>
      <% else %>
        <!-- ユーザーがログインしていない場合 -->
        <div class="collapse navbar-collapse" id="Navber">
          <!-- メニューアイテム -->
          <ul class="navbar-nav mr-auto">
            <!-- ログインページへのリンク -->
            <li class="nav-item">
              <%= link_to 'ログイン', new_user_session_path, class: "nav-link" %>
            </li>
            <!-- 新規登録ページへのリンク -->
            <li class="nav-item">
              <%= link_to '新規登録', new_user_registration_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      <% end %>
    </nav>

    <% if flash[:notice]%>
      <!-- 成功時のフラッシュメッセージを表示します -->
      <div class="alert alert-primary" role="alert"><strong><%= notice %></strong></div>
    <% end %>

    <% if flash[:alert]%>
      <!-- エラー時のフラッシュメッセージを表示します -->
      <div class="alert alert-danger" role="alert"><strong><%= alert %></strong></div>
    <% end %>

    <%= yield %>
  </body>
</html>

src/app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <!-- エラーメッセージを表示するアラート -->
  <div class="alert alert-danger" role="alert">
    <!-- エラーの数を表示 -->
    <h4 class="alert-heading"><%= pluralize(@user.errors.count, "error") %></h4>
    <!-- エラーメッセージの説明 -->
    <p><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</p>
    <hr>
    <p class="mb-0">
      <!-- 全てのエラーメッセージを繰り返し表示 -->
      <% @user.errors.full_messages.each do |message| %>
        <!-- 各エラーメッセージをリストアイテムとして表示 -->
        <li><%= message %></li>
      <% end %>
    </p>
  </div>
<% end %>

<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h2>編集</h2>
      <!-- @userの情報を用いてフォームを生成 -->
      <%= form_for @user do |f| %>
        <div class="form-group">
          <label>ユーザー名</label>
          <!-- ユーザー名の入力フィールド -->
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <label>メールアドレス</label>
          <!-- メールアドレスの入力フィールド -->
          <%= f.text_field :email, class: "form-control" %>
        </div>
        <div>
          <!-- フォームの送信ボタン -->
          <%= f.submit class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

src/app/views/users/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-7 mx-auto">
      <div class="card">
        <div class="card-body">
          <!-- ユーザー名を表示 -->
          <!-- current_user.name: 現在ログインしているユーザーの名前を表示します。 -->
          <h5 class="card-title"><%= current_user.name %></h5>
          <!-- メールアドレスを表示 -->
          <!-- current_user.email: 現在ログインしているユーザーのメールアドレスを表示します。 -->
          <h6 class="card-subtitle mb-2 text-muted"><%= current_user.email %></h6>
          <!-- ユーザー編集へのリンク -->
          <%= link_to 'ユーザー編集', edit_user_path %>
        </div>
      </div>
    </div>
  </div>
</div>